temp:
  res: [1, 2, 3]
  cnn: [1, 2, 3]
self_tcn:
  len_global: [1] #[2] #[1, 2, 3, 4, 5, 6, 7] #[2, 4, 6, 7] #[1, 2, 3, 4, 5, 6, 7]
  len_local: [3] #[5] #[1, 2, 3, 4, 5, 6, 7] #[2, 4, 6, 7] #[1, 2, 3, 4, 5, 6, 7]
  neighbor_size: [2] #[1] #[1, 2] #[1, 2]
  res: [2, 6] #[2, 6, 8, 12]
  cnn: [6]
  tcn: [2] #[1, 2, 3, 4, 5, 6, 7]
  nb_stacks: [2]
  lr: [1e-4]
  BN: [1]
self_tcn_min:
  len_local: [1, 2, 3, 4, 5, 6, 7]
  neighbor_size: [1, 2]
  num_tcn: [2, 3, 4]
  nb_stacks: [2]
  lr: [1e-4]
self_tcn_nog:
  len_local: [1, 2, 3, 4, 5, 6, 7]
  neighbor_size: [1, 2]
  num_tcn: [2, 4]
  nb_stacks: [2]
  num_cnn: [6]
  BN: [1]
  lr: [1e-4]
self_tcn_nog_rdw:
  len_recent: [3, 4, 5]
  len_daily: [4]
  len_week: [4]
  neighbor_size: [2]
  num_tcn: [2]
  nb_stacks: [2]
  num_cnn: [6]
  lr: [5e-4, 1e-4, 5e-5, 1e-5]
  BN: [1]
#####################
ha:
  len_local: [1, 2, 3, 4, 5, 6, 7]
  neighbor_size: [1, 2]
arima:
  region_len: [50, 100, 150, 200]
  seq_len: [10, 40, 70, 100, 130]
xgb:
  #region_len: [50, 100, 150, 200]
  len_local: [7]
  neighbor_size: [2]
  #seq_len: [10, 40, 70, 100, 130]
  deep: [1800, 2100, 2400]
cnn:
  len_local: [6] #[1, 2, 3, 4, 5, 6, 7]
  neighbor_size: [1] #[1, 2]
  cnn: [6] #[2, 4, 6]
  lr: [1e-4] #[5e-4, 1e-4, 5e-5]
  BN: [1] #[0, 1]
convlstm:
  len_local: [1, 2, 3, 4, 5, 6, 7]
  neighbor_size: [1, 2]
  stack_convlstm: [1] # [6] #[2, 4, 6]
  lr: [1e-4] #[5e-4, 1e-4, 5e-5]
stres:
  len_close: [3]
  len_trend: [2] #[1, 2, 3]
  len_period: [2] #[1, 2, 3]
  neighbor_size: [1] #[1, 2]
  res: [12] # res: [12]
  lr: [1e-4]
stdn:
  att_lstm_num: [3]
  att_lstm_seq_len: [3, 5, 7] # [7]
  lstm_seq_len: [7] # [3, 5, 7] # [7]
  flow_gate_len: [2]
  neighbor_size: [1, 2]
  #lr: [1e-3]
astgcn:
  neighbor_size: [1]
  K: [3]
  num_of_features: [1]
  num_for_prediction: [1]
  points_per_hour: [2]
  num_of_weeks: [2, 3, 4]
  num_of_days: [2, 3, 4]
  num_of_hours: [2, 3, 4]
  lr: [1e-2]
#######################
self:
  len_global: [1, 2, 3, 4, 5, 6, 7]
  len_local: [1, 2, 3, 4, 5, 6, 7]
  neighbor_size: [1, 2]
  res: [12] #[2, 4, 6, 8, 10, 12]
  cnn: [6] #[2, 4, 6]
  lr: [1e-4] #[5e-4, 1e-4, 5e-5]
  BN: [1] #[0, 1]
self_nog:
  len_local: [1, 2, 3, 4, 5, 6, 7]
  neighbor_size: [1, 2]
  res: [12] # res: [2, 4, 6, 8, 10, 12]
  cnn: [6] # cnn: [2, 4, 6]
  lr: [1e-4] # lr: [5e-4, 1e-4, 5e-5]
  BN: [1] # BN: [0, 1]
self_lstm:
  len_global: [1, 2, 3, 4, 5, 6, 7]
  len_local: [1, 2, 3, 4, 5, 6, 7]
  neighbor_size: [1, 2]
  res: [12] # res: [2, 4, 6, 8, 10, 12]
  cnn: [6] # cnn: [2, 4, 6]
  lr: [1e-4] # lr: [5e-4, 1e-4, 5e-5]
  BN: [1] # BN: [0, 1]
self_convlstm:
  len_global: [1, 2, 3, 4, 5, 6, 7]
  len_local: [1, 2, 3, 4, 5, 6, 7]
  neighbor_size: [1, 2]
  res: [12] # res: [2, 4, 6, 8, 10, 12]
  cnn: [6] # cnn: [2, 4, 6]
  lr: [1e-4] # lr: [5e-4, 1e-4, 5e-5]
  BN: [1] # BN: [0, 1]
self_da:
  len_global: [1, 2, 3, 4, 5, 6, 7]
  len_local: [1, 2, 3, 4, 5, 6, 7]
  neighbor_size: [1, 2]
  res: [12] # res: [2, 4, 6, 8, 10, 12]
  cnn: [6] # cnn: [2, 4, 6]
  lr: [1e-4] # lr: [5e-4, 1e-4, 5e-5]
  BN: [1] # BN: [0, 1]
self_la:
  len_global: [1, 2, 3, 4, 5, 6, 7]
  len_local: [1, 2, 3, 4, 5, 6, 7]
  neighbor_size: [1, 2]
  res: [12] # res: [2, 4, 6, 8, 10, 12]
  cnn: [6] # cnn: [2, 4, 6]
  lr: [1e-4] # lr: [5e-4, 1e-4, 5e-5]
  BN: [1] # BN: [0, 1]

